/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Aditya
 */
public class PrintLibraryCard extends javax.swing.JFrame {

    /**
     * Creates new form PrintIDCard
     */
    public PrintLibraryCard() {
        initComponents();
    }

    
    //Method to fetch the Student details from Database and display it to the Student details panel
    private void GetStudentDetails()
    {
        String RegistrationNo =txt_RegistrationNo.getText();
        
        try
        {
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from student_details where RegistrationNo = ?");
            pst.setString(1,RegistrationNo);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next())
            {
                lbl_RegistrationNo.setText(rs.getString("RegistrationNo"));
                lbl_Name.setText(rs.getString("Name"));
                lbl_MobileNo.setText(rs.getString("MobileNo"));
                lbl_Department.setText(rs.getString("Department"));
                lbl_Semester.setText(rs.getString("Semester"));
            }
            else
            {
                lbl_RegistrationNo.setText("");
                lbl_Name.setText("");
                lbl_MobileNo.setText("");
                lbl_Department.setText("");
                lbl_Semester.setText("");
                JOptionPane.showMessageDialog(this,"Invalid Regisration No");
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panel_print = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_Semester = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_RegistrationNo = new javax.swing.JLabel();
        lbl_Name = new javax.swing.JLabel();
        lbl_MobileNo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_Department = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_RegistrationNo = new app.bolivia.swing.JCTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btn_Find = new rojerusan.RSMaterialButtonCircle();
        btn_Print = new rojerusan.RSMaterialButtonCircle();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_print.setBackground(new java.awt.Color(255, 204, 102));
        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        panel_print.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 500, 5));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("Semester :");
        panel_print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));

        lbl_Semester.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        panel_print.add(lbl_Semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 270, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel5.setText("Name :");
        panel_print.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel6.setText("Mobile No :");
        panel_print.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel7.setText(" Registration No :");
        panel_print.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        lbl_RegistrationNo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        panel_print.add(lbl_RegistrationNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 270, 30));

        lbl_Name.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        panel_print.add(lbl_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 270, 30));

        lbl_MobileNo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        panel_print.add(lbl_MobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 270, 30));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel21.setText("Department :");
        panel_print.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        lbl_Department.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        panel_print.add(lbl_Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 270, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel4.setText("Library Card");
        panel_print.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 260, 90));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/SGP Logo.png"))); // NOI18N
        jLabel8.setText("Siliguri Govt. Polytechnic");
        panel_print.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 410, 60));

        jPanel2.add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 480, 680));

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_RegistrationNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_RegistrationNo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_RegistrationNo.setPlaceholder("Enter Registration No");
        txt_RegistrationNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_RegistrationNoFocusLost(evt);
            }
        });
        txt_RegistrationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RegistrationNoActionPerformed(evt);
            }
        });
        jPanel5.add(txt_RegistrationNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 370, 70));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 30));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 110, 50));

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel2.setText("Issue Library Card");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 330, -1));

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 5));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel19.setText("Enter Registration No");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 260, 40));

        btn_Find.setText("find");
        btn_Find.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FindActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 250, 80));

        btn_Print.setText("print");
        btn_Print.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btn_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrintActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 250, 80));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 430, 680));

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel11.setText("Back");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/LibraryCard.jpeg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 260, 220));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-icon.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 220, 430, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 680));

        setSize(new java.awt.Dimension(1287, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txt_RegistrationNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RegistrationNoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_RegistrationNoFocusLost

    private void txt_RegistrationNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RegistrationNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_RegistrationNoActionPerformed

    private void btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FindActionPerformed
        // TODO add your handling code here:
        if(txt_RegistrationNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Enter Regisration No");
        }
        else
        {
           
           GetStudentDetails();
        }
    }//GEN-LAST:event_btn_FindActionPerformed

    private void btn_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrintActionPerformed
        // TODO add your handling code here:
        //To Print the Library Card
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            @Override
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.5,0.5);
                
                panel_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
        boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }

    }//GEN-LAST:event_btn_PrintActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintLibraryCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintLibraryCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintLibraryCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintLibraryCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintLibraryCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btn_Find;
    private rojerusan.RSMaterialButtonCircle btn_Print;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_Department;
    private javax.swing.JLabel lbl_MobileNo;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_RegistrationNo;
    private javax.swing.JLabel lbl_Semester;
    private javax.swing.JPanel panel_print;
    private app.bolivia.swing.JCTextField txt_RegistrationNo;
    // End of variables declaration//GEN-END:variables
}
