/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Aditya
 */
public class ViewAllRecord extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllRecord
     */
    DefaultTableModel model;
    protected ViewAllRecord() {
        initComponents();
        SetAllDetailsToTable();
    }

    //Method to set Details to Table
    private void SetAllDetailsToTable()
    {
        try
        {
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from issue_book");
            
            while(rs.next())
            {
                
                String ID = rs.getString("ID");
                String BookName=rs.getString("BookName");
                String RegistrationNo=rs.getString("RegistrationNo");
                String Name=rs.getString("Name");
                String IssueDate=rs.getString("IssueDate");
                String DueDate=rs.getString("DueDate");
                String Status=rs.getString("Status");
                
                Object[] obj = {ID,BookName,RegistrationNo,Name,IssueDate,DueDate,Status};
                model = (DefaultTableModel) tbl_ViewAllDetails.getModel();
                model.addRow(obj);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    //Method to fetch the Record Using Date-Fields
    private boolean Search()
    {
        boolean IsFound=false;
        java.util.Date UFromDate =txt_FromDate.getDate();
        java.util.Date UToDate=txt_ToDate.getDate();
        
        long l1=UFromDate.getTime();
        long l2=UToDate.getTime();
        
        java.sql.Date SFromDate = new java.sql.Date(l1);
        java.sql.Date SToDate = new java.sql.Date(l2);
        
        try
        {
            Connection con = DBConnection.getConnection();
            String sql = "select * from issue_book where IssueDate >= ? and DueDate <= ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setDate(1,SFromDate);
            pst.setDate(2,SToDate);
            
            ResultSet rs = pst.executeQuery();
                while(rs.next())
                {
                    IsFound=true;
                    String ID = rs.getString("ID");
                    String BookName=rs.getString("BookName");
                    String RegistrationNo=rs.getString("RegistrationNo");
                    String Name=rs.getString("Name");
                    String IssueDate=rs.getString("IssueDate");
                    String DueDate=rs.getString("DueDate");
                    String Status=rs.getString("Status");
                
                    Object[] obj = {ID,BookName,RegistrationNo,Name,IssueDate,DueDate,Status};
                    model = (DefaultTableModel) tbl_ViewAllDetails.getModel();
                    model.addRow(obj);
                }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return IsFound;
    }
    
    //Method to Clear Data from Table
    private void ClearTable()
    {
        DefaultTableModel model = (DefaultTableModel) tbl_ViewAllDetails.getModel();
        model.setRowCount(0);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_ToDate = new com.toedter.calendar.JDateChooser();
        txt_FromDate = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();
        Panel_Table = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_ViewAllDetails = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 420, 5));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel13.setText("View All Records");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 310, 100));

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 30));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 110, 50));

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel11.setText("Back");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("To Date :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 100, 40));

        txt_ToDate.setDateFormatString("yyyy-MM-dd");
        txt_ToDate.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jPanel2.add(txt_ToDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 270, 40));

        txt_FromDate.setDateFormatString("yyyy-MM-dd");
        txt_FromDate.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jPanel2.add(txt_FromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 270, 40));

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("From Date :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 130, 40));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(255, 0, 0));
        rSMaterialButtonCircle1.setText("search");
        rSMaterialButtonCircle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle1MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, 150, 70));

        rSMaterialButtonCircle2.setText("All");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 200, 150, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 270));

        Panel_Table.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_ViewAllDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Issue ID", "Book Name", "Registration No", "Student Name", "Issue Date", "Due Date", "Status"
            }
        ));
        tbl_ViewAllDetails.setColorBackgoundHead(new java.awt.Color(0, 204, 255));
        tbl_ViewAllDetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_ViewAllDetails.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tbl_ViewAllDetails.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        tbl_ViewAllDetails.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        tbl_ViewAllDetails.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        tbl_ViewAllDetails.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbl_ViewAllDetails.setRowHeight(25);
        tbl_ViewAllDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ViewAllDetailsMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_ViewAllDetails);

        Panel_Table.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1240, 320));

        getContentPane().add(Panel_Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1290, 530));

        setSize(new java.awt.Dimension(1288, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void tbl_ViewAllDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ViewAllDetailsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_ViewAllDetailsMouseClicked

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        // TODO add your handling code here:
        if(txt_FromDate.getDate() != null && txt_ToDate.getDate() != null)
        {
            if(Search() == true)
            {
                ClearTable();
                Search(); 
            }
            else
            {
                ClearTable();
                JOptionPane.showMessageDialog(this,"No Records Found");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Please Select a Date");
        }
        
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void rSMaterialButtonCircle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle1MouseClicked

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        // TODO add your handling code here:
        ClearTable();
        SetAllDetailsToTable();
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Table;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane5;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private rojerusan.RSTableMetro tbl_ViewAllDetails;
    private com.toedter.calendar.JDateChooser txt_FromDate;
    private com.toedter.calendar.JDateChooser txt_ToDate;
    // End of variables declaration//GEN-END:variables
}
